[package]
name = "praktikum3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# avl_tree = "0.2.0"
rand = "0.8"